/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Lucas Silva
 */
public class CadFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadFornecedor
     */
    public CadFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Cadastrar Fornecedor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 390, 30);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fornecedor");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 80, 14);

        jLabel3.setText("Nome:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 60, 60, 30);

        jLabel4.setText("CNPJ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(400, 60, 80, 30);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(60, 60, 290, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(460, 60, 260, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 50, 770, 130);

        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Informações para contato");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 10, 230, 14);

        jLabel6.setText("E-mail");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 44, 70, 20);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(70, 40, 310, 30);

        jLabel7.setText("Tel1");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 80, 60, 30);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(70, 80, 240, 30);

        jLabel8.setText("Tel2");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(360, 80, 40, 30);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(400, 80, 250, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 200, 770, 130);

        jPanel4.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Informações de endereço");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 10, 170, 30);

        jLabel10.setText("CEP");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 44, 40, 20);
        jPanel4.add(jTextField6);
        jTextField6.setBounds(50, 40, 120, 30);

        jLabel11.setText("Cidade");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(220, 44, 70, 20);
        jPanel4.add(jTextField7);
        jTextField7.setBounds(270, 40, 160, 30);

        jLabel12.setText("Bairro");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(460, 40, 60, 30);
        jPanel4.add(jTextField8);
        jTextField8.setBounds(510, 40, 230, 30);

        jLabel13.setText("Rua");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(20, 94, 30, 20);
        jPanel4.add(jTextField9);
        jTextField9.setBounds(50, 90, 330, 30);

        jLabel14.setText("Nº");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(420, 94, 40, 20);
        jPanel4.add(jTextField10);
        jTextField10.setBounds(450, 90, 80, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 350, 770, 130);

        jButton2.setText("cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 510, 90, 30);

        jButton3.setText("Fechar");
        jPanel1.add(jButton3);
        jButton3.setBounds(700, 510, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(834, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
