/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.FornecedorController;
import Controller.ProdutoController;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Silva
 */
public class CadProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadProduto
     */
    public void carregar_fornecedores(){
        
        String fornecedores[] = new FornecedorController().listar_fornecedores();
        
        for(String fornecedor: fornecedores){
            _fornecedor.addItem(fornecedor);
        }
        
    }
    
    public CadProduto() {
        initComponents();
        carregar_fornecedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        _imei = new javax.swing.JTextField();
        _cod_barras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        _valor_un = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        _valor_re = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        _fornecedor = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        _modelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        _gb_ram = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        _cor = new javax.swing.JTextField();
        arm = new javax.swing.JLabel();
        _armazenamento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        _quantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setText("IMEI");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 30, 40, 30);

        jLabel2.setText("Codigo de barras");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 30, 100, 20);
        jPanel2.add(_imei);
        _imei.setBounds(70, 30, 160, 30);
        jPanel2.add(_cod_barras);
        _cod_barras.setBounds(420, 30, 130, 30);

        jLabel3.setText("Valor Unitario de Compra");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 70, 150, 20);
        jPanel2.add(_valor_un);
        _valor_un.setBounds(30, 100, 150, 30);

        jLabel4.setText("Valor de revenda");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(240, 70, 110, 30);
        jPanel2.add(_valor_re);
        _valor_re.setBounds(240, 100, 160, 30);

        jLabel5.setText("Fornecedor");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(440, 70, 180, 30);

        _fornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vazio" }));
        _fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _fornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(_fornecedor);
        _fornecedor.setBounds(440, 100, 190, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 120, 660, 140);

        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Informações do produto");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 10, 210, 20);

        jLabel7.setText("Modelo");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 50, 60, 20);

        _modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _modeloActionPerformed(evt);
            }
        });
        jPanel3.add(_modelo);
        _modelo.setBounds(30, 80, 180, 30);

        jLabel8.setText("GB RAM");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(250, 44, 80, 30);
        jPanel3.add(_gb_ram);
        _gb_ram.setBounds(250, 80, 90, 30);

        jLabel9.setText("Cor");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(520, 50, 60, 14);
        jPanel3.add(_cor);
        _cor.setBounds(520, 80, 120, 30);

        arm.setText("Armazenamento");
        jPanel3.add(arm);
        arm.setBounds(380, 50, 90, 14);
        jPanel3.add(_armazenamento);
        _armazenamento.setBounds(380, 80, 100, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 270, 660, 150);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Cadastrar Produto");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 20, 540, 30);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(710, 60, 170, 230);

        jButton1.setText("Imagem");
        jPanel1.add(jButton1);
        jButton1.setBounds(710, 310, 170, 40);

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(600, 430, 120, 30);

        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(740, 430, 130, 30);

        jPanel4.setLayout(null);

        jLabel11.setText("Quantos produtos desse você deseja adicionar ao estoque?");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(20, 10, 350, 30);
        jPanel4.add(_quantidade);
        _quantidade.setBounds(370, 10, 110, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 60, 660, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(932, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void _modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__modeloActionPerformed

    private void _fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__fornecedorActionPerformed


    }//GEN-LAST:event__fornecedorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String cor = _cor.getText();
        String modelo = _modelo.getText();
        String imei = _imei.getText();
        String codigo_barras = _cod_barras.getText();
        String fornecedor = String.valueOf(_fornecedor.getSelectedItem()); // valueOf evita valores nulos

        String gb_ram = _gb_ram.getText();
        String armazenamento = _armazenamento.getText();

        String valor_unitario = _valor_un.getText();
        String valor_revenda = _valor_re.getText();
        String quantidade = _quantidade.getText();
        
        ProdutoController pc = new ProdutoController();

        int rs = JOptionPane.showConfirmDialog(null, "Deseja prosseguir com cadastro?");
        
        if (rs == JOptionPane.YES_OPTION) {
            pc.cadastrar_produto(cor, modelo, imei, codigo_barras, fornecedor, gb_ram, armazenamento, valor_unitario, valor_revenda, quantidade);
        } else {
            JOptionPane.showMessageDialog(null, "Processo de cadastro cancelado!", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new GerProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _armazenamento;
    private javax.swing.JTextField _cod_barras;
    private javax.swing.JTextField _cor;
    private javax.swing.JComboBox<String> _fornecedor;
    private javax.swing.JTextField _gb_ram;
    private javax.swing.JTextField _imei;
    private javax.swing.JTextField _modelo;
    private javax.swing.JTextField _quantidade;
    private javax.swing.JTextField _valor_re;
    private javax.swing.JTextField _valor_un;
    private javax.swing.JLabel arm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
