/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.PessoaController;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Silva
 */
public class CadPessoa extends javax.swing.JFrame {

    /**
     * Creates new form CadCliente
     */
    public CadPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmd_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmd_cpf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmd_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmd_tel1 = new javax.swing.JTextField();
        cmd_tel2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmd_cep = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmd_cidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmd_bairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmd_rua = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmd_numero = new javax.swing.JTextField();
        cmd_estado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmd_cad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 18, 55));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Pessoa");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(23, 11, 190, 14);

        jLabel3.setText("Nome");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 40, 50, 30);
        jPanel2.add(cmd_nome);
        cmd_nome.setBounds(78, 43, 191, 28);

        jLabel4.setText("CPF/CNPJ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(290, 40, 90, 30);
        jPanel2.add(cmd_cpf);
        cmd_cpf.setBounds(350, 40, 180, 28);

        jLabel16.setText("Você deseja cadastrar como fornecedor?");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(540, 20, 260, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "não", "sim" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(580, 40, 120, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 70, 780, 110);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Cadastrar Pessoa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 223, 46);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Informações para contato");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(19, 11, 200, 14);

        jLabel6.setText("E-mail");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 54, 70, 20);
        jPanel3.add(cmd_email);
        cmd_email.setBounds(90, 50, 266, 29);

        jLabel7.setText("Tel 2");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(390, 97, 50, 30);

        jLabel8.setText("Tel1");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 100, 50, 29);
        jPanel3.add(cmd_tel1);
        cmd_tel1.setBounds(90, 100, 233, 30);
        jPanel3.add(cmd_tel2);
        cmd_tel2.setBounds(430, 100, 210, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 190, 780, 150);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Informações de endereço");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 10, 230, 14);

        jLabel10.setText("CEP");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 34, 30, 30);
        jPanel4.add(cmd_cep);
        cmd_cep.setBounds(60, 30, 120, 30);

        jLabel11.setText("Cidade");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(460, 30, 60, 30);
        jPanel4.add(cmd_cidade);
        cmd_cidade.setBounds(510, 30, 140, 30);

        jLabel12.setText("Bairro");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(20, 70, 60, 50);
        jPanel4.add(cmd_bairro);
        cmd_bairro.setBounds(60, 80, 210, 30);

        jLabel13.setText("Rua");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(290, 80, 30, 30);
        jPanel4.add(cmd_rua);
        cmd_rua.setBounds(320, 80, 300, 30);

        jLabel14.setText("Nº");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(640, 80, 50, 30);
        jPanel4.add(cmd_numero);
        cmd_numero.setBounds(670, 80, 80, 30);
        jPanel4.add(cmd_estado);
        cmd_estado.setBounds(270, 30, 140, 30);

        jLabel15.setText("Estado");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(220, 30, 70, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 360, 780, 130);

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(700, 520, 110, 30);

        cmd_cad.setText("Cadastrar");
        cmd_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_cadActionPerformed(evt);
            }
        });
        jPanel1.add(cmd_cad);
        cmd_cad.setBounds(570, 520, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(856, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_cadActionPerformed
        // TODO add your handling code here:
        PessoaController c = new PessoaController();

        //
        String nome = cmd_nome.getText();
        String cpf = cmd_cpf.getText();

        // informações de contato
        String email = cmd_email.getText();
        String tel1 = cmd_tel1.getText();
        String tel2 = cmd_tel2.getText();

        // informações de endereço
        String cep = cmd_cep.getText();
        String estado = cmd_estado.getText();
        String cidade = cmd_cidade.getText();
        String bairro = cmd_bairro.getText();
        String rua = cmd_rua.getText();

        String numero = cmd_numero.getText();
        
        int tipo_de_pessoa = jComboBox2.getSelectedIndex();
        
        if (tipo_de_pessoa == 0) {
            
            int result = JOptionPane.showConfirmDialog(null, "Você está cadastrando " + nome + " como cliente, deseja prosseguir?");
            
            if (result == JOptionPane.YES_OPTION) {
                c.cadastrar_pessoa(nome, cpf, email, tel1, tel2, cep, estado, cidade, bairro, rua, numero, tipo_de_pessoa);
            } else {
                JOptionPane.showMessageDialog(null, "Você cancelou operação!");
            }
        
        } else {

            int result = JOptionPane.showConfirmDialog(null, "Você está cadastrando " + nome + " como fornecedor, deseja continuar?");
            
            if (result == JOptionPane.YES_OPTION) {
                c.cadastrar_pessoa(nome, cpf, email, tel1, tel2, cep, estado, cidade, bairro, rua, numero,tipo_de_pessoa);
            } else {
                JOptionPane.showMessageDialog(null, "Você cancelou operação!");
            }
        }


    }//GEN-LAST:event_cmd_cadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new GerCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cmd_bairro;
    private javax.swing.JButton cmd_cad;
    private javax.swing.JTextField cmd_cep;
    private javax.swing.JTextField cmd_cidade;
    private javax.swing.JTextField cmd_cpf;
    private javax.swing.JTextField cmd_email;
    private javax.swing.JTextField cmd_estado;
    private javax.swing.JTextField cmd_nome;
    private javax.swing.JTextField cmd_numero;
    private javax.swing.JTextField cmd_rua;
    private javax.swing.JTextField cmd_tel1;
    private javax.swing.JTextField cmd_tel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
