/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.FornecedorController;
import Controller.PessoaController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lucas Silva
 */
public class GerCliente extends javax.swing.JFrame {

    /**
     * Creates new form GerCliente
     */
    private DefaultTableModel tb1;
    private PessoaController ps;
    private FornecedorController fn;
    
    public GerCliente() {
        initComponents();
        
        this.tb1 = (DefaultTableModel) jTable1.getModel(); 
        this.ps = new PessoaController();
        this.fn = new FornecedorController();
        
        this.setRow();
    }

    public void setRow() {

        while (tb1.getRowCount() > 0) {
            tb1.removeRow(0);
        }

        ArrayList<String[]> clientes = ps.buscar_amostra();

        clientes.forEach((cliente) -> {
            tb1.addRow(cliente);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        _fornecedores = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 18, 55));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Gerenciar Pessoas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 410, 29);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Nova Pessoa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 70, 110, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF/CNPJ     OU");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 70, 100, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 70, 40, 30);

        _search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                _searchFocusGained(evt);
            }
        });
        _search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _searchMouseClicked(evt);
            }
        });
        _search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _searchActionPerformed(evt);
            }
        });
        jPanel1.add(_search);
        _search.setBounds(520, 70, 190, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(730, 70, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "cpf/cnpj", "email", "tel1", "tel2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 790, 300);

        jButton3.setText("Editar");
        jPanel1.add(jButton3);
        jButton3.setBounds(540, 450, 110, 30);

        jButton4.setText("Fechar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(700, 450, 110, 30);

        _fornecedores.setForeground(new java.awt.Color(255, 255, 255));
        _fornecedores.setText("Apenas Fornecedores");
        _fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _fornecedoresActionPerformed(evt);
            }
        });
        jPanel1.add(_fornecedores);
        _fornecedores.setBounds(640, 30, 170, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(868, 567));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new CadPessoa().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // faz busca de resultados na base
        if (_search.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você está fazendo uma busca vazia!", null, JOptionPane.WARNING_MESSAGE);
        } else {
            
            // limpa a tabela
            while (tb1.getRowCount() > 0) {
                tb1.removeRow(0);
            }

            ps.busca_cliente(_search.getText()).forEach((cliente) -> {
                tb1.addRow(cliente);
            });

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void _fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__fornecedoresActionPerformed
        // TODO add your handling code here:

        if (_fornecedores.isSelected()) {

            while (tb1.getRowCount() > 0) {
                tb1.removeRow(0);
            }

            ArrayList<String[]> fornecedores = fn.buscar_amostra();

            fornecedores.forEach((fornecedor) -> {
                tb1.addRow(fornecedor);
            });

        } else {
            setRow();
        }
    }//GEN-LAST:event__fornecedoresActionPerformed

    private void _searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__searchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event__searchActionPerformed

    private void _searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__searchMouseClicked

    }//GEN-LAST:event__searchMouseClicked

    private void _searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event__searchFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event__searchFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox _fornecedores;
    private javax.swing.JTextField _search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
